### ISSUE TITLE
Rip C#

### ISSUE THREAD

**Issue by Itzbenz** [o7-Fire/SayFuckCountriesInEveryMedia#36]
![image](https://user-images.githubusercontent.com/49940811/156114949-4da745f4-32f1-49ab-89a6-00c2ed1f86a7.png)

literally exists https://github.com/o7-Fire/SayFuckCountriesInEveryMedia/tree/main/discord/C%23

**Comment by Itzbenz** [comment]
@thisgary

**Comment by shadow01148** [comment]
do manual idiot

- nev

**Comment by garylkz** [comment]
![](https://cdn.discordapp.com/attachments/911438810825515049/948194316298358824/fuck_you.gif)
