### ISSUE TITLE
there is too much countries

### ISSUE THREAD

**Issue by NexitySecond** [o7-Fire/SayFuckCountriesInEveryMedia#40]
problem: too many countries causing too many controversies and too many politics

solution: remove the ones that have a lot of controversies such as ukraine

**Comment by shadow01148** [comment]
based and redpilled

**Comment by Volas171** [comment]
unbased, this issue must be closed due to reasons: too heated,too much controversy, no drama here please.

**Comment by NexitySecond** [comment]
reopened because issue still exists
