### ISSUE TITLE
"Impossible" symbol is too small

### ISSUE THREAD

**Issue by Itzbenz** [o7-Fire/SayFuckCountriesInEveryMedia#66]
proposing other Unicode symbol like ∆
![Screenshot](https://user-images.githubusercontent.com/49940811/190950016-51431ec4-d748-4843-8383-87a5efbeb0a0.png)

**Comment by Itzbenz** [comment]
@wotgary

**Comment by garylkz** [comment]
You need to look at the big picture
![h](https://media.discordapp.net/attachments/921595377923268708/1021312986050215986/IMG_20220909_231948.jpg)
