### ISSUE TITLE
priorities

### ISSUE THREAD

**Issue by shadow01148** [o7-Fire/SayFuckCountriesInEveryMedia#67]
it better to keep your priority straight

- [ ] Complete Ruby
- [ ] Complete Rust
- [ ] Complete Dart
- [ ] Complete Crystal
- [ ] Complete Clojure
- [ ] Add loops for certain languages
- [x] Force gary to fix his shit
- [ ] Perl
- [ ] Add bash support (wtf) 
- [ ]  Does @shadow01148 scripts work?

**Comment by Itzbenz** [comment]
use TODO.md or Project

**Comment by Itzbenz** [comment]
or readme

**Comment by shadow01148** [comment]
above is based

**Comment by wotgary** [comment]
> use TODO.md or Project

Bro, README.md exists for a reason

**Comment by shadow01148** [comment]
> > use TODO.md or Project
> 
> Bro, README.md exists for a reason

i am reporting you to my teacher

**Comment by shadow01148** [comment]
mf fuck you
