### ISSUE TITLE
Use HTML for the table

### ISSUE THREAD

**Issue by shadow01148** [o7-Fire/SayFuckCountriesInEveryMedia#70]
# Use HTML

[https://developer.mozilla.org/en-US/docs/Learn/HTML/Tables/Basics](url)

which one do you think is better in raw 

(example)
<table>
  <tr>
    <td>&nbsp;</td>
    <td>Knocky</td>
    <td>Flor</td>
    <td>Ella</td>
    <td>Juan</td>
  </tr>
  <tr>
    <td>Breed</td>
    <td>Jack Russell</td>
    <td>Poodle</td>
    <td>Streetdog</td>
    <td>Cocker Spaniel</td>
  </tr>
  <tr>
    <td>Age</td>
    <td>16</td>
    <td>9</td>
    <td>10</td>
    <td>5</td>
  </tr>
  <tr>
    <td>Owner</td>
    <td>Mother-in-law</td>
    <td>Me</td>
    <td>Me</td>
    <td>Sister-in-law</td>
  </tr>
  <tr>
    <td>Eating Habits</td>
    <td>Eats everyone's leftovers</td>
    <td>Nibbles at food</td>
    <td>Hearty eater</td>
    <td>Will eat till he explodes</td>
  </tr>
</table>

or 

| Media | Bash | C | C# | C++ | Clojure | Cobol | Crystal | Dart | Go | Java | Javascript | Julia | Kotlin | Lua | Nim | Perl | Powershell | Python | Ruby | Rust | Swift |
| --- | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: |
| Discord | ✓ | ✓ | ✓ | ✓ | ✓ | [<div>-</div>](discord/Cobol/IMPOSSIBLE.txt) | ✓ | ✓ | ✓ | ✓ | ✓ | ✓ | ✓ | ✓ | ✓ | X | ✓ | ✓ | ✓ | ✓ | ✓ |
| Github | [<div>-</div>](github/Bash/IMPOSSIBLE.txt) | X | X | X | X | X | [<div>-</div>](github/Crystal/IMPOSSIBLE.txt) | X | X | X | X | X | X | X | X | X | ✓ | ✓ | ✓ | X | X |
| Kahoot | [<div>-</div>](kahoot/Bash/IMPOSSIBLE.txt) | X | X | X | X | X | [<div>-</div>](kahoot/Crystal/IMPOSSIBLE.txt) | [<div>-</div>](kahoot/Dart/IMPOSSIBLE.txt) | X | X | X | X | X | X | X | X | [<div>-</div>](kahoot/Powershell/IMPOSSIBLE.txt) | ✓ | [<div>-</div>](kahoot/Ruby/IMPOSSIBLE.txt) | X | [<div>-</div>](kahoot/Swift/IMPOSSIBLE.txt) |
| Stdout | ✓ | ✓ | ✓ | ✓ | ✓ | ✓ | ✓ | ✓ | X | ✓ | ✓ | X | X | X | ✓ | X | ✓ | ✓ | ✓ | ✓ | ✓ |
| Twitter | ✓ | X | ✓ | X | ✓ | X | ✓ | X | X | X | ✓ | X | X | ✓ | X | ✓ | ✓ | ✓ | ✓ | X | X |
## HTML Advantages:

Looks better

Readable

Flexible on style

## Disadvantages:

Makes the .md file longer than it already is (wtf?)

**Comment by Volas171** [comment]
you should kill yourself and revert back to 61af0ce907e98df0029c5eb0db971e7b068f3441

**Comment by Itzbenz** [comment]
and as you know XML is highly standardized and there is a lot of parser and builder for it, it is no doubt better than homemade garbage, but I'm not in mood to touch HTML

**Comment by Itzbenz** [comment]
also I fail to see where HTML look better

**Comment by shadow01148** [comment]
> you should kill yourself and revert back to [61af0ce](https://github.com/o7-Fire/SayFuckCountriesInEveryMedia/commit/61af0ce907e98df0029c5eb0db971e7b068f3441)

I shouldnt kill myself and fuck you

**Comment by shadow01148** [comment]
> also I fail to see where HTML look better

It is more readable in raw as opposed to markdown

**Comment by Itzbenz** [comment]
> > also I fail to see where HTML look better
> 
> It is more readable in raw

no thanks
